### PR TITLE
Add some useful links on README

### PR DESCRIPTION
**Pull request by kngwyu**

### CODE REVIEW

**Review by jiegillet — APPROVED** [review]
That is super helpful, thank you! I didn't expect a pull review :)

**Comment by jiegillet** [comment]
I looked at your profile, you are very active on GitHub, that's super cool.

Do you think OIST people would be interested in learning Rust?

**Comment by kngwyu** [comment]
>  you are very active on GitHub

Yeah, I *was* active until recently

> Do you think OIST people would be interested in learning Rust?

I don't think so. Rust is very good in some use cases like writing fast native apps or web servers. However, in fast and modern numerical computation, we need to leverage the power of GPU and native GPU libraries such as CUDA, and GPU/CUDA support is definitely a week point in Rust. Still, Python (or Julia in some cases) is better in scientific programming, though we can use Rust for speeding up Python apps.

**Comment by jiegillet** [comment]
I see, thank you for sharing your expertise :)

We have done some Julia courses, but I would like to offer some more advanced Python courses.

**Comment by kngwyu** [comment]
>  I would like to offer some more advanced Python courses.

I would like to help with it! Some modern Python patterns (`dataclasses` and type annotation) and GPU computation frameworks (e.g., JAX) would be useful.

**Pull request merged**
